/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/**
 * Generated from FastAPI OpenAPI (repo-local generator).
 * Source: backend/app/main.py (create_app().openapi())
 */

export interface paths {
    "/api/market/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Candles */
        get: operations["get_market_candles_api_market_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/ingest/candle_closed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Candle Closed */
        post: operations["ingest_candle_closed_api_market_ingest_candle_closed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/ingest/candle_forming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Candle Forming */
        post: operations["ingest_candle_forming_api_market_ingest_candle_forming_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draw/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draw Delta
         * @description Unified draw delta (v1 base):
         *     - instruction_catalog_patch + active_ids (overlay instructions)
         *     - series_points (indicator line points; v0 returns empty for now)
         */
        get: operations["get_draw_delta_api_draw_delta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/factor/slices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Factor Slices
         * @description v0 debug endpoint to inspect which factor snapshots are available at time t.
         *
         *     Note: v0 supports:
         *     - pivot: history.major from factor events, head.minor computed on the fly
         *     - pen: history.confirmed from factor events
         */
        get: operations["get_factor_slices_api_factor_slices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frame/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get World Frame Live
         * @description Unified world frame (live): latest aligned world state.
         *     v1 implementation is a projection of existing factor_slices + draw/delta.
         */
        get: operations["get_world_frame_live_api_frame_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frame/at_time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get World Frame At Time
         * @description Unified world frame (replay point query): aligned world state at time t.
         */
        get: operations["get_world_frame_at_time_api_frame_at_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delta/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll World Delta
         * @description v1 world delta (live):
         *     - Uses draw/delta cursor as the minimal incremental source (compat projection).
         *     - Emits at most 1 record per poll (if cursor advances); otherwise returns empty records.
         */
        get: operations["poll_world_delta_api_delta_poll_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/whitelist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Whitelist */
        get: operations["get_market_whitelist_api_market_whitelist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/debug/ingest_state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Ingest State */
        get: operations["get_market_ingest_state_api_market_debug_ingest_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/top_markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top Markets */
        get: operations["get_top_markets_api_market_top_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/top_markets/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Top Markets */
        get: operations["stream_top_markets_api_market_top_markets_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Strategies */
        get: operations["get_backtest_strategies_api_backtest_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/pair_timeframes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Pair Timeframes */
        get: operations["get_backtest_pair_timeframes_api_backtest_pair_timeframes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Backtest Job */
        post: operations["run_backtest_job_api_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestPairTimeframesResponse */
        BacktestPairTimeframesResponse: {
            /** Pair */
            pair: string;
            /** Trading Mode */
            trading_mode: string;
            /** Datadir */
            datadir: string;
            /** Available Timeframes */
            available_timeframes: string[];
        };
        /** BacktestRunRequest */
        BacktestRunRequest: {
            /** Strategy Name */
            strategy_name: string;
            /** Pair */
            pair: string;
            /** Timeframe */
            timeframe: string;
            /** Timerange */
            timerange?: string | null;
        };
        /** BacktestRunResponse */
        BacktestRunResponse: {
            /** Ok */
            ok: boolean;
            /** Exit Code */
            exit_code: number;
            /** Duration Ms */
            duration_ms: number;
            /** Command */
            command: string[];
            /** Stdout */
            stdout: string;
            /** Stderr */
            stderr: string;
        };
        /** CandleClosed */
        CandleClosed: {
            /**
             * Candle Time
             * @description Unix seconds (candle open time)
             */
            candle_time: number;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /** DrawCursorV1 */
        DrawCursorV1: {
            /**
             * Version Id
             * @default 0
             */
            version_id: number;
            /**
             * Point Time
             * @description Optional cursor for series_points (time-based)
             */
            point_time?: number | null;
        };
        /** DrawDeltaV1 */
        DrawDeltaV1: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Series Id */
            series_id: string;
            /** To Candle Id */
            to_candle_id: string | null;
            /** To Candle Time */
            to_candle_time: number | null;
            /** Active Ids */
            active_ids?: string[];
            /** Instruction Catalog Patch */
            instruction_catalog_patch?: components["schemas"]["OverlayInstructionPatchItemV1"][];
            /** Series Points */
            series_points?: {
                [key: string]: components["schemas"]["PlotLinePointV1"][];
            };
            next_cursor: components["schemas"]["DrawCursorV1"];
        };
        /** FactorMetaV1 */
        FactorMetaV1: {
            /** Series Id */
            series_id: string;
            /**
             * Epoch
             * @default 0
             */
            epoch: number;
            /** At Time */
            at_time: number;
            /** Candle Id */
            candle_id: string;
            /** Factor Name */
            factor_name: string;
        };
        /** FactorSliceV1 */
        FactorSliceV1: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** History */
            history?: {
                [key: string]: unknown;
            };
            /** Head */
            head?: {
                [key: string]: unknown;
            };
            meta: components["schemas"]["FactorMetaV1"];
        };
        /** GetCandlesResponse */
        GetCandlesResponse: {
            /** Series Id */
            series_id: string;
            /** Server Head Time */
            server_head_time: number | null;
            /** Candles */
            candles: components["schemas"]["CandleClosed"][];
        };
        /** GetFactorSlicesResponseV1 */
        "GetFactorSlicesResponseV1-Input": {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Series Id */
            series_id: string;
            /** At Time */
            at_time: number;
            /** Candle Id */
            candle_id: string | null;
            /** Factors */
            factors?: string[];
            /** Snapshots */
            snapshots?: {
                [key: string]: components["schemas"]["FactorSliceV1"];
            };
        };
        /** GetFactorSlicesResponseV1 */
        "GetFactorSlicesResponseV1-Output": {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Series Id */
            series_id: string;
            /** At Time */
            at_time: number;
            /** Candle Id */
            candle_id: string | null;
            /** Factors */
            factors?: string[];
            /** Snapshots */
            snapshots?: {
                [key: string]: components["schemas"]["FactorSliceV1"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestCandleClosedRequest */
        IngestCandleClosedRequest: {
            /** Series Id */
            series_id: string;
            candle: components["schemas"]["CandleClosed"];
        };
        /** IngestCandleClosedResponse */
        IngestCandleClosedResponse: {
            /** Ok */
            ok: boolean;
            /** Series Id */
            series_id: string;
            /** Candle Time */
            candle_time: number;
        };
        /** IngestCandleFormingRequest */
        IngestCandleFormingRequest: {
            /** Series Id */
            series_id: string;
            candle: components["schemas"]["CandleClosed"];
        };
        /** IngestCandleFormingResponse */
        IngestCandleFormingResponse: {
            /** Ok */
            ok: boolean;
            /** Series Id */
            series_id: string;
            /** Candle Time */
            candle_time: number;
        };
        /** OverlayInstructionPatchItemV1 */
        OverlayInstructionPatchItemV1: {
            /** Version Id */
            version_id: number;
            /** Instruction Id */
            instruction_id: string;
            /** Kind */
            kind: string;
            /** Visible Time */
            visible_time: number;
            /** Definition */
            definition?: {
                [key: string]: unknown;
            };
        };
        /** PlotLinePointV1 */
        PlotLinePointV1: {
            /**
             * Time
             * @description Unix seconds (candle open time)
             */
            time: number;
            /** Value */
            value: number;
        };
        /** StrategyListResponse */
        StrategyListResponse: {
            /** Strategies */
            strategies: string[];
        };
        /** TopMarketItem */
        TopMarketItem: {
            /** Exchange */
            exchange: string;
            /** Market */
            market: string;
            /** Symbol */
            symbol: string;
            /** Symbol Id */
            symbol_id: string;
            /** Base Asset */
            base_asset: string;
            /** Quote Asset */
            quote_asset: string;
            /** Last Price */
            last_price?: number | null;
            /** Quote Volume */
            quote_volume?: number | null;
            /** Price Change Percent */
            price_change_percent?: number | null;
        };
        /** TopMarketsResponse */
        TopMarketsResponse: {
            /** Exchange */
            exchange: string;
            /** Market */
            market: string;
            /** Quote Asset */
            quote_asset: string;
            /** Limit */
            limit: number;
            /** Generated At Ms */
            generated_at_ms: number;
            /** Cached */
            cached: boolean;
            /** Items */
            items: components["schemas"]["TopMarketItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorldCursorV1 */
        WorldCursorV1: {
            /**
             * Id
             * @default 0
             */
            id: number;
        };
        /** WorldDeltaPollResponseV1 */
        WorldDeltaPollResponseV1: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Series Id */
            series_id: string;
            /** Records */
            records?: components["schemas"]["WorldDeltaRecordV1-Output"][];
            next_cursor: components["schemas"]["WorldCursorV1"];
        };
        /** WorldDeltaRecordV1 */
        "WorldDeltaRecordV1-Input": {
            /** Id */
            id: number;
            /** Series Id */
            series_id: string;
            /** To Candle Id */
            to_candle_id: string;
            /** To Candle Time */
            to_candle_time: number;
            draw_delta: components["schemas"]["DrawDeltaV1"];
            factor_slices?: components["schemas"]["GetFactorSlicesResponseV1-Input"] | null;
        };
        /** WorldDeltaRecordV1 */
        "WorldDeltaRecordV1-Output": {
            /** Id */
            id: number;
            /** Series Id */
            series_id: string;
            /** To Candle Id */
            to_candle_id: string;
            /** To Candle Time */
            to_candle_time: number;
            draw_delta: components["schemas"]["DrawDeltaV1"];
            factor_slices?: components["schemas"]["GetFactorSlicesResponseV1-Output"] | null;
        };
        /** WorldStateV1 */
        WorldStateV1: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Series Id */
            series_id: string;
            time: components["schemas"]["WorldTimeV1"];
            factor_slices: components["schemas"]["GetFactorSlicesResponseV1-Output"];
            draw_state: components["schemas"]["DrawDeltaV1"];
        };
        /** WorldTimeV1 */
        WorldTimeV1: {
            /**
             * At Time
             * @description Requested time (unix seconds)
             */
            at_time: number;
            /**
             * Aligned Time
             * @description Aligned closed candle_time (floor)
             */
            aligned_time: number;
            /** Candle Id */
            candle_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_market_candles_api_market_candles_get: {
        parameters: {
            query: {
                series_id: string;
                since?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCandlesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_candle_closed_api_market_ingest_candle_closed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestCandleClosedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestCandleClosedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_candle_forming_api_market_ingest_candle_forming_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestCandleFormingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestCandleFormingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draw_delta_api_draw_delta_get: {
        parameters: {
            query: {
                series_id: string;
                cursor_version_id?: number;
                window_candles?: number;
                /** @description Optional replay upper-bound (Unix seconds) */
                at_time?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrawDeltaV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_factor_slices_api_factor_slices_get: {
        parameters: {
            query: {
                series_id: string;
                at_time: number;
                window_candles?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetFactorSlicesResponseV1-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_world_frame_live_api_frame_live_get: {
        parameters: {
            query: {
                series_id: string;
                window_candles?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldStateV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_world_frame_at_time_api_frame_at_time_get: {
        parameters: {
            query: {
                series_id: string;
                at_time: number;
                window_candles?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldStateV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_world_delta_api_delta_poll_get: {
        parameters: {
            query: {
                series_id: string;
                after_id?: number;
                limit?: number;
                window_candles?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldDeltaPollResponseV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_whitelist_api_market_whitelist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    get_market_ingest_state_api_market_debug_ingest_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_top_markets_api_market_top_markets_get: {
        parameters: {
            query: {
                exchange?: string;
                market: string;
                quote_asset?: string;
                limit?: number;
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMarketsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_top_markets_api_market_top_markets_stream_get: {
        parameters: {
            query: {
                exchange?: string;
                market: string;
                quote_asset?: string;
                limit?: number;
                interval_s?: number;
                max_events?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_strategies_api_backtest_strategies_get: {
        parameters: {
            query?: {
                recursive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_pair_timeframes_api_backtest_pair_timeframes_get: {
        parameters: {
            query: {
                pair: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestPairTimeframesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_job_api_backtest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
